apiVersion: v1
kind: Secret
metadata:
  name: {{ template "patroni.fullname" . }}
  labels:
    app: {{ template "patroni.fullname" . }}
    chart: {{ template "patroni.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  password-superuser: {{ randAlphaNum 30 | b64enc | quote }}
  password-admin: {{ randAlphaNum 30 | b64enc | quote }}
  password-standby: {{ randAlphaNum 30 | b64enc | quote }}
  app-db-name: {{ .Values.credentials.appDbName | b64enc }}
  app-db-username: {{ .Values.credentials.appDbUserame | b64enc }}
  app-db-password: {{ randAlphaNum 30 | b64enc | quote }}
