apiVersion: v1
name: NR Patroni (CrunchyDB)
description: 'A CrunchyDB cluster'
version: 0.2.5
appVersion: 0.1.0
home: https://timcsaky.github.io/nr-patroni-chart
dependencies:
  - name: crunchy-postgres
    version: 0.5.0
    repository: https://bcgov.github.io/crunchy-postgres/
  - name: crunchy-postgres-tools
    version: 0.3.0
    repository: https://bcgov.github.io/crunchy-postgres/